# Generated by Django 3.2.3 on 2021-06-19 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_name', models.CharField(max_length=50)),
                ('p_weight', models.IntegerField()),
                ('p_BP', models.IntegerField()),
                ('p_gender', models.IntegerField(choices=[('m', 'male'), ('f', 'female'), ('o', 'others')], max_length=1)),
                ('p_phone', models.IntegerField()),
                ('p_aadhar', models.IntegerField()),
                ('p_address', models.TextField(max_length=100)),
                ('admitted_date', models.DateTimeField()),
                ('discharge_date', models.DateTimeField()),
            ],
        ),
    ]
