# Generated by Django 3.2.3 on 2021-06-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_patient_p_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='OP',
            fields=[
                ('o_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_id', models.IntegerField()),
                ('o_date', models.DateTimeField()),
                ('o_pname', models.CharField(max_length=50)),
                ('symptoms', models.CharField(max_length=50)),
                ('doctor_assign', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patient_details',
        ),
    ]
