# Generated by Django 3.2.3 on 2021-06-24 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210621_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='op',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.op'),
        ),
    ]
