# Generated by Django 3.2.3 on 2021-06-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_op'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='p_BP',
            field=models.CharField(max_length=30),
        ),
    ]
