# Generated by Django 3.2.3 on 2021-06-24 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_patient_p_bp'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='patient',
            table=None,
        ),
    ]
