# Generated by Django 3.2.3 on 2021-06-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_patient_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='p_weight',
            new_name='p_age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='p_BP',
        ),
        migrations.AddField(
            model_name='patient',
            name='visits',
            field=models.IntegerField(null=True),
        ),
    ]
