# Generated by Django 3.2.3 on 2021-06-25 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210625_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='op',
        ),
    ]
