# Generated by Django 3.2.3 on 2021-06-28 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_patient_op'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='op',
            name='p_id',
        ),
    ]
