# Generated by Django 3.2.3 on 2021-07-02 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_op_p_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_id', models.IntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('experiance', models.IntegerField(null=True)),
                ('specialization', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=50)),
                ('test_description', models.CharField(max_length=1000)),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('visit_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date_time', models.DateTimeField()),
                ('is_next_visit', models.BooleanField(default=False)),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('medicine_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.medicine')),
                ('op_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.op')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.patient')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.test')),
            ],
        ),
    ]
